Update rust container
eclipse-set/browser pull request #6
Opened 2023-08-14 08:32 UTC by TruongQuangSB

- The [PR-build#5](https://github.com/eclipse-set/build/pull/5) should be merge and the workflows _Build and push docker image_ im build-repo should be successful before this PR
- Change rust docker image source to github container

2023-08-16 11:52 UTC, PetersNils commented
/license-check
This is just a test unrelated to this PR to check if #10 worked.

2023-08-17 07:17 UTC, TruongQuangSB commented
/request-license-review

2023-08-17 09:20 UTC, PetersNils requested changes

2023-08-17 09:20 UTC, PetersNils commented on .github/workflows/ci.yml
> +
```suggestion
```

2023-08-17 09:20 UTC, PetersNils commented on .github/workflows/ci.yml
> +    container: ghcr.io/${{ needs.get-organisation-name.outputs.organisation }}/rust-x86_64-pc-windows-gnu:latest
```suggestion
    container: ghcr.io/eclipse-set/rust-x86_64-pc-windows-gnu:latest
```

2023-08-17 09:20 UTC, PetersNils commented on .github/workflows/ci.yml
> +
I guess we should get rid of these variables for simplicity.
```suggestion
```

2023-08-17 09:22 UTC, PetersNils commented on .github/workflows/ci.yml
>      runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-22.04
```

2023-08-17 09:24 UTC, TruongQuangSB commented on .github/workflows/ci.yml
> +
ok

2023-08-17 09:25 UTC, PetersNils commented on .github/workflows/ci.yml
>        run: rustup target add x86_64-pc-windows-gnu
This is already done within the docker container
```suggestion
```

2023-08-17 09:27 UTC, PetersNils commented on .github/workflows/ci.yml
>      - name: Set up Rust
```suggestion
```

2023-08-17 09:31 UTC, PetersNils approved these changes
OK

2023-08-17 09:58 UTC, PetersNils commented
Currently the required docker image is private and not accessible. I'll wait with merging this until the permissions are fixed.

2023-08-24 13:54 UTC, TruongQuangSB commented
/license-check

2023-09-01 10:15 UTC, PetersNils approved these changes
With the Rust docker image now being public we can merge this.

2023-09-01 10:16 UTC, merged